
swagger: "2.0"
info:
  description: This is the swagger file that defines generated api
  version: "dev/0.0.1"
  title: API-Nlppy Generated
consumes:
  - application/json
produces:
  - application/json

definitions:
  NLPPY:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: Id of the element
      createdAt:
        type: string
      updatedAt:
        type: string
      
      active:
        type: boolean

      name:
        type: string

      value:
        type: number



#base path for server application
basePath: /api
# Paths supported by the server application
paths:
  /nlppy:
    get:
      operationId: api.listAll
      tags:
        - NLPPY
      summary: Read the entire list of nlppy
      description: Read the list of nlppy
      responses:
        200:
          description: Successfully read nlppy list operation
          schema:
            $ref: '#/definitions/NLPPY'
    post:
      operationId: api.createOne
      tags:
        - NLPPY
      summary: Create a NLPPY and add it to the nlppy list
      description: Create a new NLPPY in the nlppy list
      parameters:
        - name: object
          in: body
          description: NLPPY to create
          required: True
          schema:
            $ref: '#/definitions/NLPPY'
      responses:
        201:
          description: Successfully created NLPPY in list

  /nlppy/{id}:
    get:
      operationId: api.getOne
      tags:
        - NLPPY 
      summary: Read one NLPPY from the nlppy list
      description: Read one NLPPY from the nlppy list
      parameters:
        - name: id
          in: path
          description: Unique model identifier for NLPPY 
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            $ref: '#/definitions/NLPPY'
    put:
      operationId: api.updateOne
      tags:
        - NLPPY
      summary: Update a NLPPY in nlppy 
      description: Update a NLPPY in nlppy 
      parameters:
        - name: id
          in: path
          description: Unique model identifier for NLPPY
          type: string
          required: True
        - name: object
          in: body
          schema:
            $ref: '#/definitions/NLPPY'
      responses:
        200:
          description: Successfully updated NLPPY
    delete:
      operationId: api.deleteOne
      tags:
        - NLPPY
      summary: Delete a NLPPY from the nlppy list
      description: Delete a person
      parameters:
        - name: id
          in: path
          type: string
          required: True
          description: Unique model identifier for NLPPY
      responses:
        200:
          description: Successfully deleted a NLPPY
